[build]
  command = "npm run build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  package = "netlify-plugin-cache-nextjs"

[context.production.environment]
NEXT_SERVERLESS = "true"
NODE_ENV = "production"
